# Konfigurasi dasar Jekyll
title: "Nama Blog Anda"
description: "Deskripsi singkat tentang blog Anda."
baseurl: ""  # Jika di root domain, biarkan kosong. Jika di subfolder, misal "/blog"
url: "https://contoh.com"  # Ganti dengan URL situs Anda

# Informasi penulis (opsional)
author:
  name: "Nama Anda"
  email: "email@contoh.com"

# Direktori sumber dan tujuan
source: .
destination: ./_site
include: ["_pages"]  # Jika ada folder khusus yang harus dimasukkan

# Layout
permalink: /:categories/:title/  # Struktur URL postingan

# Plugins
plugins:
  - jekyll-sass-converter
  - jekyll-paginate

# Konfigurasi Paginasi
paginate: 5  # Jumlah post per halaman
paginate_path: "/page:num/"  # Format URL untuk paginasi

# Konfigurasi SASS/SCSS
sass:
  style: compressed  # Bisa diganti ke expanded untuk debugging
  sass_dir: assets/_sass  # Direktori SASS

# Koleksi khusus (opsional)
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Kategori dan Tag (opsional)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nama Anda"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude (file yang tidak di-render oleh Jekyll)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .git
  - .jekyll-cache
  - .sass-cache
  - _config_dev.yml  # Jika ada konfigurasi khusus untuk development

# Konfigurasi Markdown
markdown: kramdown
kramdown:
  input: GFM  # Gunakan GitHub Flavored Markdown
  auto_ids: true
  toc_levels: 1..3  # Level heading yang muncul di daftar isi

# Mode Server
port: 4000
host: 0.0.0.0